import React, { useState, useMemo, useEffect } from 'react';
import './ModelExplanation.css';

const baseParams = {
    sysTok: { name: "Supervisor System Prompt", val: 500, type: 'input', location: "Workflow Config", desc: "Instructions defining the supervisor's persona and routing constraints." },
    regTok: { name: "Worker Registry", val: 200, type: 'input', location: "Workflow Config", desc: "The list of available worker tools exposed to the supervisor." },
    hitRate: { name: "Estimated Cache Hit Rate", val: 0.50, type: 'input', location: "Global Config", desc: "The percentage of the prompt expected to hit the model's token cache." },
    base: { name: "Worker Base Prompt", val: 400, type: 'input', location: "Worker Config", desc: "The starting instructions and context given to the worker agent." },
    schema: { name: "Tool Schema Tokens", val: 250, type: 'input', location: "Worker Config", desc: "The JSON schema defining the tools the worker is allowed to call." },
    obs: { name: "Tool Observation Tokens", val: 1000, type: 'input', location: "Global Config", desc: "The tokens returned by the environment after the agent executes a tool." },
    workerAvgOutput: { name: "Worker Avg Output", val: 300, type: 'input', location: "Worker Config", desc: "The tokens generated by the worker (thoughts + actions)." },
    retries: { name: "Max Retries per Cycle", val: 1, type: 'input', location: "Global Config", desc: "Extra cycles triggered by schema validation failures or API timeouts." },
    CU_Multiplier: { name: "Capacity Unit Multiplier", val: 1.90, type: 'input', location: "Global Config", desc: "The conversion rate from AI tokens to SAP GenAI Capacity Units." },
    
    historyTok: { name: "Accumulated History Tokens", type: 'computed', source: "History Context", location: "Runtime State", desc: "Tracks the growing context of observations from previous hops." },
    supIn: { name: "Supervisor Input Tokens", type: 'computed', source: "Step 1", location: "Runtime State", desc: "Total tokens sent in the supervisor routing request." },
    cacheHit: { name: "Supervisor Cached Tokens", type: 'computed', source: "Step 2", location: "Runtime State", desc: "Tokens that are cached and billed at a discounted rate." },
    billable: { name: "Supervisor Billable Tokens", type: 'computed', source: "Step 2", location: "Runtime State", desc: "Tokens that are billed at the full input rate." },
    
    hopIn: { name: "Worker Hop Input Tokens", type: 'computed', source: "Hop Input", location: "Runtime State", desc: "The total size of the worker's prompt for this hop." },
    hopCache: { name: "Worker Hop Cached Tokens", type: 'computed', source: "Hop Split", location: "Runtime State", desc: "Worker tokens that hit the cache." },
    hopBillable: { name: "Worker Hop Billable Tokens", type: 'computed', source: "Hop Split", location: "Runtime State", desc: "Worker tokens billed at the full rate." },
    hopOut: { name: "Worker Hop Output Tokens", type: 'computed', source: "Hop Output", location: "Runtime State", desc: "The output generated by the worker in this hop." },
    
    cycleTokens: { name: "Total Processed Tokens", type: 'computed', source: "Aggregator", location: "Runtime State", desc: "The aggregated sum of all tokens across the supervisor and all worker hops." },
    cycleCU: { name: "SAP Capacity Units (CU)", type: 'computed', source: "Final Result", location: "Runtime State", desc: "The final SAP Capacity Units used for billing." }
};

export default function ModelExplanation() {
    const [hops, setHops] = useState(1);
    const [currentStep, setCurrentStep] = useState(0);
    const [visibleStages, setVisibleStages] = useState({ incoming: false, raw: false, sub: false, res: false });

    // Trigger animation sequence when step changes
    useEffect(() => {
        setVisibleStages({ incoming: false, raw: false, sub: false, res: false });
        
        const t1 = setTimeout(() => setVisibleStages(s => ({ ...s, incoming: true })), 50);
        const t2 = setTimeout(() => setVisibleStages(s => ({ ...s, raw: true })), 200);
        const t3 = setTimeout(() => setVisibleStages(s => ({ ...s, sub: true })), 800);
        const t4 = setTimeout(() => setVisibleStages(s => ({ ...s, res: true })), 1400);

        return () => { clearTimeout(t1); clearTimeout(t2); clearTimeout(t3); clearTimeout(t4); };
    }, [currentStep, hops]);

    const changeHops = (delta) => {
        const newHops = hops + delta;
        if (newHops >= 1 && newHops <= 10) {
            setHops(newHops);
            setCurrentStep(0);
        }
    };

    // Calculate all steps dynamically
    const stepsData = useMemo(() => {
        const s = [];
        const stateParams = JSON.parse(JSON.stringify(baseParams));
        
        // Initialize computed values to 0
        Object.keys(stateParams).forEach(k => {
            if (stateParams[k].type === 'computed') stateParams[k].val = 0;
        });

        // Helper functions for string generation, using the current stateParams at time of creation
        const v = (key) => {
            const p = stateParams[key];
            const locText = p.location ? `<br/><small style="color:#a5b4fc">${p.location}</small>` : '';
            return `<span class="me-var-hint ${p.type}">${key}<span class="me-tooltip-content"><b>${p.name}: ${p.val}</b><br/><span style="opacity:0.9">${p.desc}</span>${locText}</span></span>`;
        };
        const val = (key) => {
            const p = stateParams[key];
            const locText = p.location ? `<br/><small style="color:#a5b4fc">${p.location}</small>` : '';
            return `<span class="me-var-hint ${p.type}">${p.val}<span class="me-tooltip-content"><b>${p.name} (${key})</b><br/><span style="opacity:0.9">${p.desc}</span>${locText}</span></span>`;
        };

        const addStep = (title, description, inputsUsed, getRaw, getSub, getRes, updateState) => {
            s.push({
                title, description, inputsUsed,
                rawHtml: getRaw(),
                subHtml: getSub(),
                resHtml: getRes(),
                stateBefore: JSON.parse(JSON.stringify(stateParams))
            });
            // Apply updates to running state
            const updates = updateState();
            for (const [key, value] of Object.entries(updates)) {
                stateParams[key].val = value;
            }
        };

        addStep(
            "Supervisor Input Tokens",
            "Calculate the total tokens sent to the supervisor router for routing logic.",
            ["sysTok", "regTok", "historyTok"],
            () => `supIn = ${v('sysTok')} + ${v('regTok')} + ${v('historyTok')}`,
            () => `supIn = ${val('sysTok')} + ${val('regTok')} + ${val('historyTok')}`,
            () => `supIn = ${stateParams.sysTok.val + stateParams.regTok.val + stateParams.historyTok.val}`,
            () => ({ "supIn": stateParams.sysTok.val + stateParams.regTok.val + stateParams.historyTok.val })
        );

        addStep(
            "Supervisor Cache Splitting",
            "Apply the estimated cache hit rate to determine billable tokens vs discounted cached tokens.",
            ["supIn", "hitRate"],
            () => `cacheHit = Math.round(${v('supIn')} * ${v('hitRate')})<br/>billable = ${v('supIn')} - cacheHit`,
            () => `cacheHit = Math.round(${val('supIn')} * ${val('hitRate')})<br/>billable = ${val('supIn')} - Math.round(${val('supIn')} * ${val('hitRate')})`,
            () => {
                const ch = Math.round(stateParams.supIn.val * stateParams.hitRate.val);
                return `cacheHit = ${ch}<br/>billable = ${stateParams.supIn.val - ch}`;
            },
            () => {
                const ch = Math.round(stateParams.supIn.val * stateParams.hitRate.val);
                return { "cacheHit": ch, "billable": stateParams.supIn.val - ch };
            }
        );

        for (let h = 1; h <= hops; h++) {
            addStep(
                `Worker Hop ${h}: Input Tokens`,
                `Calculate the context window size for the worker agent's reasoning cycle ${h}. Note how history tokens accumulate.`,
                ["base", "schema", "historyTok", "obs"],
                () => `hopIn = ${v('base')} + ${v('schema')} + ${v('historyTok')} + (${h} - 1) * ${v('obs')}`,
                () => `hopIn = ${val('base')} + ${val('schema')} + ${val('historyTok')} + (${h - 1} * ${val('obs')})`,
                () => `hopIn = ${stateParams.base.val + stateParams.schema.val + stateParams.historyTok.val + ((h-1) * stateParams.obs.val)}`,
                () => ({ "hopIn": stateParams.base.val + stateParams.schema.val + stateParams.historyTok.val + ((h-1) * stateParams.obs.val) })
            );

            addStep(
                `Worker Hop ${h}: Cache Splitting`,
                "Cache deductions apply identically to the worker prompt.",
                ["hopIn", "hitRate"],
                () => `hopCache = Math.round(${v('hopIn')} * ${v('hitRate')})<br/>hopBillable = ${v('hopIn')} - hopCache`,
                () => `hopCache = Math.round(${val('hopIn')} * ${val('hitRate')})<br/>hopBillable = ${val('hopIn')} - Math.round(${val('hopIn')} * ${val('hitRate')})`,
                () => {
                    const ch = Math.round(stateParams.hopIn.val * stateParams.hitRate.val);
                    return `hopCache = ${ch}<br/>hopBillable = ${stateParams.hopIn.val - ch}`;
                },
                () => {
                    const ch = Math.round(stateParams.hopIn.val * stateParams.hitRate.val);
                    return { "hopCache": ch, "hopBillable": stateParams.hopIn.val - ch };
                }
            );

            addStep(
                `Worker Hop ${h}: Output Tokens`,
                "The worker generates an action, API payload, or final response.",
                ["workerAvgOutput"],
                () => `hopOut = ${v('workerAvgOutput')}`,
                () => `hopOut = ${val('workerAvgOutput')}`,
                () => `hopOut = ${stateParams.workerAvgOutput.val}`,
                () => ({ "hopOut": stateParams.workerAvgOutput.val })
            );

            addStep(
                `Worker Hop ${h}: Retries & Aggregate`,
                `Worker tokens are multiplied by potential API retries. Supervisor tokens are routed once and do not incur retries.`,
                ["cycleTokens", "retries", "hopIn", "hopOut"],
                () => `cycleTokens = ${v('cycleTokens')} + (${v('hopIn')} + ${v('hopOut')}) * (1 + ${v('retries')})`,
                () => `cycleTokens = ${val('cycleTokens')} + (${val('hopIn')} + ${val('hopOut')}) * (1 + ${val('retries')})`,
                () => `cycleTokens = ${stateParams.cycleTokens.val + (stateParams.hopIn.val + stateParams.hopOut.val) * (1 + stateParams.retries.val)}`,
                () => ({ "cycleTokens": stateParams.cycleTokens.val + (stateParams.hopIn.val + stateParams.hopOut.val) * (1 + stateParams.retries.val) })
            );

            if (h < hops) {
                addStep(
                    `Worker Hop ${h}: Update History`,
                    `Append the tool observation and output to the context history for Hop ${h+1}.`,
                    ["historyTok", "hopOut", "obs"],
                    () => `historyTok = ${v('historyTok')} + Math.round((${v('hopOut')} + ${v('obs')}) * 0.7)`,
                    () => `historyTok = ${val('historyTok')} + Math.round((${val('hopOut')} + ${val('obs')}) * 0.7)`,
                    () => `historyTok = ${stateParams.historyTok.val + Math.round((stateParams.hopOut.val + stateParams.obs.val) * 0.7)}`,
                    () => ({ "historyTok": stateParams.historyTok.val + Math.round((stateParams.hopOut.val + stateParams.obs.val) * 0.7) })
                );
            }
        }

        addStep(
            "Finalize Cycle Tokens",
            "Add the single supervisor routing request to the accumulated worker cycle tokens.",
            ["cycleTokens", "supIn"],
            () => `cycleTokens = ${v('cycleTokens')} + ${v('supIn')}`,
            () => `cycleTokens = ${val('cycleTokens')} + ${val('supIn')}`,
            () => `cycleTokens = ${stateParams.cycleTokens.val + stateParams.supIn.val}`,
            () => ({ "cycleTokens": stateParams.cycleTokens.val + stateParams.supIn.val })
        );

        addStep(
            "Convert to SAP Capacity Units",
            "GenAI Hub abstracts token costs into a universal Capacity Unit (CU).",
            ["cycleTokens", "CU_Multiplier"],
            () => `cycleCU = (${v('cycleTokens')}) * ${v('CU_Multiplier')}`,
            () => `cycleCU = (${val('cycleTokens')}) * ${val('CU_Multiplier')}`,
            () => `cycleCU = ${Math.round(stateParams.cycleTokens.val * stateParams.CU_Multiplier.val)}`,
            () => ({ "cycleCU": Math.round(stateParams.cycleTokens.val * stateParams.CU_Multiplier.val) })
        );

        return s;
    }, [hops]);

    const activeStep = stepsData[currentStep];
    const activeParams = activeStep.stateBefore;

    return (
        <div className="model-explanation">
            <div className="me-panel-left">
                <div className="me-panel-title">Calculation Steps</div>
                
                <div className="me-hops-control">
                    <label>Reasoning Hops (L)</label>
                    <div className="me-hops-input-group">
                        <button className="me-hops-btn" onClick={() => changeHops(-1)}>-</button>
                        <span className="me-ui-hops-val">{hops}</span>
                        <button className="me-hops-btn" onClick={() => changeHops(1)}>+</button>
                    </div>
                </div>

                <div id="steps-container">
                    {stepsData.map((step, idx) => (
                        <div 
                            key={idx}
                            className={`me-step-card ${idx === currentStep ? 'active' : ''} ${idx < currentStep ? 'completed' : ''}`}
                            onClick={() => setCurrentStep(idx)}
                        >
                            <div className="me-step-card-num">STEP {idx + 1}</div>
                            <div className="me-step-card-title">{step.title}</div>
                        </div>
                    ))}
                </div>
            </div>

            <div className="me-panel-right">
                <div className="me-step-header">
                    <div className="me-step-nav">
                        <button className="me-compact-btn" disabled={currentStep === 0} onClick={() => setCurrentStep(c => c - 1)}>❮</button>
                        <div className="me-step-counter">STEP {currentStep + 1} OF {stepsData.length}</div>
                        <button className="me-compact-btn" disabled={currentStep === stepsData.length - 1} onClick={() => setCurrentStep(c => c + 1)}>❯</button>
                    </div>
                    <h2 className="me-step-title">{activeStep.title}</h2>
                    <p className="me-step-desc">{activeStep.description}</p>
                </div>

                <div className="me-calculation-stage">
                    <div className="me-math-box">
                        <div className={`me-incoming-wrapper ${visibleStages.incoming ? 'visible' : ''}`}>
                            <div className="me-inputs-grid">
                                {activeStep.inputsUsed.map(key => {
                                    const p = activeParams[key];
                                    return (
                                        <div key={key} className={`me-data-pill ${p.type}`}>
                                            <div className="me-pill-tooltip">
                                                <div className="me-pill-tooltip-loc">{p.type === 'input' ? 'Configured in: ' : ''}{p.location}</div>
                                                {p.desc}
                                            </div>
                                            <div className="me-data-pill-header">
                                                {p.type === 'input' ? p.name : `From ${p.source}`} <span style={{opacity: 0.5}}>({key})</span>
                                            </div>
                                            <div className="me-data-pill-val">{p.val}</div>
                                        </div>
                                    );
                                })}
                            </div>
                            {activeStep.inputsUsed.length > 0 && <div className="me-data-arrow"></div>}
                        </div>

                        <div className={`me-math-line me-math-raw ${visibleStages.raw ? 'visible' : ''}`} dangerouslySetInnerHTML={{ __html: activeStep.rawHtml }} />
                        <div className={`me-math-line me-math-sub ${visibleStages.sub ? 'visible' : ''}`} dangerouslySetInnerHTML={{ __html: activeStep.subHtml }} />
                        <div className={`me-math-line me-math-res ${visibleStages.res ? 'visible' : ''}`} dangerouslySetInnerHTML={{ __html: activeStep.resHtml }} />
                    </div>
                </div>
            </div>
        </div>
    );
}
